#ifndef OBJ_PAUSE_H
#define OBJ_PAUSE_H

#include <stdbool.h>
#include <stdint.h>

typedef enum PauseScreen
{
	PAUSE_SCREEN_NONE,
	PAUSE_SCREEN_LYLE_WEAK,
	PAUSE_SCREEN_MAP,
	PAUSE_SCREEN_GET_MAP,
	PAUSE_SCREEN_GET_CUBE_LIFT,
	PAUSE_SCREEN_GET_CUBE_JUMP,
	PAUSE_SCREEN_GET_CUBE_KICK,
	PAUSE_SCREEN_GET_ORANGE_CUBE,
	PAUSE_SCREEN_GET_PHANTOM,
	PAUSE_SCREEN_GET_PHANTOM_DOUBLE_DAMAGE,
	PAUSE_SCREEN_GET_PHANTOM_HALF_TIME,
	PAUSE_SCREEN_GET_PHANTOM_CHEAP,
	PAUSE_SCREEN_HP_ORB_0,
	PAUSE_SCREEN_HP_ORB_1,
	PAUSE_SCREEN_HP_ORB_2,
	PAUSE_SCREEN_HP_ORB_3,
	PAUSE_SCREEN_HP_ORB_4,
	PAUSE_SCREEN_HP_ORB_5,
	PAUSE_SCREEN_HP_ORB_6,
	PAUSE_SCREEN_HP_ORB_7,
	PAUSE_SCREEN_HP_ORB_8,
	PAUSE_SCREEN_HP_ORB_9,
	PAUSE_SCREEN_HP_ORB_10,
	PAUSE_SCREEN_HP_ORB_11,
	PAUSE_SCREEN_HP_ORB_12,
	PAUSE_SCREEN_HP_ORB_13,
	PAUSE_SCREEN_HP_ORB_14,
	PAUSE_SCREEN_HP_ORB_15,
	PAUSE_SCREEN_CP_ORB_0,
	PAUSE_SCREEN_CP_ORB_1,
	PAUSE_SCREEN_CP_ORB_2,
	PAUSE_SCREEN_CP_ORB_3,
	PAUSE_SCREEN_CP_ORB_4,
	PAUSE_SCREEN_CP_ORB_5,
	PAUSE_SCREEN_CP_ORB_6,
	PAUSE_SCREEN_CP_ORB_7,
	PAUSE_SCREEN_CP_ORB_8,
	PAUSE_SCREEN_CP_ORB_9,
	PAUSE_SCREEN_CP_ORB_10,
	PAUSE_SCREEN_CP_ORB_11,
	PAUSE_SCREEN_CP_ORB_12,
	PAUSE_SCREEN_CP_ORB_13,
	PAUSE_SCREEN_CP_ORB_14,
	PAUSE_SCREEN_CP_ORB_15,
	PAUSE_SCREEN_DEBUG,
	PAUSE_SCREEN_ROOM_SELECT,
	PAUSE_SCREEN_SOUND_TEST,
	PAUSE_SCREEN_PROGRESS_EDIT,
	PAUSE_SCREEN_VRAM_VIEW,
	PAUSE_SCREEN_BUTTON_CHECK,
} PauseScreen;

void pause_set_screen(PauseScreen screen);

bool pause_want_window(void);
int16_t pause_get_debug_room_id(void);

void pause_init(void);
void pause_poll(void);


#endif  // OBJ_PAUSE_H
